package main.presentation.screens;

public enum ScreenType
{
	GAME_SELECT,
	EXHIBITION_TEAM_SELECT,
	TOURNAMENT_TEAM_SELECT,
	LEAGUE_TEAM_SELECT,
	TEAM_EDITOR,
	GAME_PLAY,
	STATS_RUSHING,
	STATS_CHECKING,
	STATS_SACKING,
	STATS_CARNAGE,
	STATS_OVERVIEW,
	STATS_MVP
}
