package main.presentation.screens;

public enum ScreenType
{
	GAME_SELECT,
	EXHIBITION_TEAM_SELECT,
	TOURNAMENT_TEAM_SELECT,
	LEAGUE_TEAM_SELECT,
	EXHIBITION_PREGAME,
	TOURNAMENT_PREGAME,
	LEAGUE_PREGAME,
	EXHIBITION_VICTORY,
	TOURNAMENT_VICTORY,
	LEAGUE_VICTORY,
	TEAM_EDITOR,
	GAME_PLAY,
	TEAM_STATS_TEAM,
	TEAM_STATS_LEADERS,
	TEAM_STATS_OVERVIEW,
	EVENT_STATS_RUSHING,	//TODO: this might become EVENT_STATS instead, assuming those screens have a manager like the team editor ones do
	EVENT_STATS_CHECKING,
	EVENT_STATS_SACKING,
	EVENT_STATS_CARNAGE,
	EVENT_STATS_OVERVIEW,
	EVENT_STATS_MVP
}
